### ISSUE TITLE
Null check operator used on a null value since Flutter 2.2.0

### ISSUE THREAD

**Issue by guenth39** [f3ath/cider#23]
Since Flutter 2.2.0 I get the following error when I run `cider bump patch -b` or `cider bump minor -b`. `cider bump build` works without problems.

```
1.1.5+103
Null check operator used on a null value
#0      CommandRunner.parse (package:args/command_runner.dart:127:51)
#1      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:36)
#2      new Future.sync (dart:async/future.dart:218:31)
#3      CommandRunner.run (package:args/command_runner.dart:112:14)
#4      Cider.run (package:cider/src/cider.dart:67:33)
#5      main (file:///Users/michaguenther/.pub-cache/hosted/pub.dartlang.org/cider-0.1.0/bin/cider.dart:6:13)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by f3ath** [comment]
Hi @guenth39 . The `-b` option is removed in cider v0.1. Please use `--keep-build` instead.

**Comment by guenth39** [comment]
Thanks for the reply. Solved the problem for me.
